version: "3"

services:
  php:
    build: ./php
    volumes:
      - ${APP_DIR}:/app
      - ./php/cache:/root/.composer/cache
    working_dir: /app

  web:
    build:
      context: ./web
      args:
        - PUBLIC_DIR
    volumes:
      # Use long form syntax to prevent unnecessary creation of files or folders.
      - type: bind
        source: ${APP_DIR}
        target: /app
    working_dir: /app

  db:
    image: mariadb:10.5
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: master