version: "3"

services:
  php:
    container_name: php
    build: ./php
    volumes:
      - ./app:/app
      - ./php/cache:/root/.composer/cache
    working_dir: /app

  apache:
    container_name: apache
    build: ./apache
    volumes:
      - ./app/public:/var/www/html
    depends_on:
      - php
    ports:
      - "8000:80"
      - "4430:443"

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
    ports:
      - "33060:3306"
