version: "3"

services:
  php:
    build: ./php
    volumes:
      - ${APP_DIR}:/app
      - ./php/cache:/root/.composer/cache
    working_dir: /app

  web:
    build: ./web
    volumes:
      - ${APP_DIR}:/var/www/html

  db:
    image: mariadb:10.5
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: master
