version: "3"

services:
  cli:
    container_name: cli
    build: ./cli
    volumes:
      - ${APP_DIR}:/app
      - ./cli/cache:/root/.composer/cache
    working_dir: /app

  web:
    container_name: web
    build: ./web
    volumes:
      - ${APP_DIR}:/var/www/html
    ports:
      - "8000:80"
      - "4430:443"

  db:
    container_name: db
    image: mariadb:10.5
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: master
    ports:
      - "33060:3306"
